#include <stdio.h>

void test_compression_roundtrip(void);
void test_block_header_validation(void);
void test_open_close(void);
void test_append_read_aggregate_csv(void);
void test_append_batch_zero_one_many(void);
void test_append_batch_multiple_blocks(void);
void test_flush_single_series(void);
void test_flush_empty_buffer(void);
void test_flush_all(void);
void test_flush_invalid_args(void);
void test_flush_before_export_csv(void);
void test_get_series_handle(void);
void test_append_handle_basic(void);
void test_append_batch_handle_basic(void);
void test_handle_invalid_args(void);
void test_handle_series_not_found(void);
void test_handle_after_reopen(void);
void test_handle_after_delete_documented_behavior(void);
void test_list_series_empty_database(void);
void test_list_series_multiple_series(void);
void test_list_series_stats_fields(void);
void test_list_series_invalid_args(void);
void test_list_series_after_reopen(void);
void test_verify_valid_database(void);
void test_verify_empty_database(void);
void test_verify_missing_metadata(void);
void test_verify_invalid_segment_filename(void);
void test_verify_truncated_segment(void);
void test_verify_invalid_args(void);
void test_corrupt_segment_magic(void);
void test_corrupt_segment_truncated(void);
void test_corrupt_segment_payload_size(void);
void test_corrupt_segment_point_count_zero(void);
void test_corrupt_segment_point_count_huge(void);
void test_corrupt_segment_timestamp_range(void);
void test_corrupt_segment_read_range_returns_error(void);
void test_corrupt_wal_checksum(void);
void test_corrupt_wal_torn_final_entry(void);
void test_corrupt_wal_batch_checksum(void);
void test_corrupt_wal_batch_torn_final_entry(void);
void test_corrupt_wal_batch_invalid_record_type(void);
void test_corrupt_wal_batch_invalid_point_count(void);
void test_random_bytes_segment_files(void);
void test_fuzz_like_random_segment_inputs(void);
void test_delete_series_basic(void);
void test_delete_series_files_removed(void);
void test_delete_series_after_reopen(void);
void test_delete_series_with_pending_wal(void);
void test_delete_one_series_keeps_others(void);
void test_delete_series_invalid_args(void);
void test_delete_series_then_recreate(void);
void test_series_stats_empty_and_buffered(void);
void test_series_stats_after_single_block_flush(void);
void test_series_stats_blocks_and_reopen(void);
void test_series_compression_stats(void);
void test_many_points_blocks_and_reopen(void);
void test_block_stats_aggregate_and_index(void);
void test_read_debug_stats_range_skip(void);
void test_read_stats_min_max_not_double_counted(void);
void test_read_range_callback_stops_full_scan(void);
void test_window_aggregate_basic(void);
void test_window_aggregate_boundary(void);
void test_window_aggregate_sparse(void);
void test_window_aggregate_empty_range(void);
void test_window_aggregate_invalid_args(void);
void test_window_aggregate_after_reopen(void);
void test_window_aggregate_multi_block(void);
void test_multiple_series(void);
void test_segment_rotation_creates_multiple_files(void);
void test_read_range_across_segments(void);
void test_aggregate_across_segments(void);
void test_reopen_rebuilds_multi_segment_index(void);
void test_wal_replay_with_segment_rotation(void);
void test_single_segment_database_still_works(void);
void test_delete_before_empty_series(void);
void test_delete_before_no_matching_segments(void);
void test_delete_before_removes_one_segment(void);
void test_delete_before_removes_multiple_segments(void);
void test_delete_before_keeps_partial_segment(void);
void test_delete_before_reopen(void);
void test_delete_before_append_after_delete(void);
void test_delete_before_wal_consistency(void);
void test_wal_recovery(void);
void test_wal_empty_replay(void);
void test_wal_incomplete_last_entry(void);
void test_wal_bad_checksum(void);
void test_wal_recovery_after_batch_append(void);
void test_wal_v2_point_recovery_compatibility(void);
void test_wal_batch_recovery_large(void);
void test_set_durability_invalid_args(void);
void test_wal_buffer_flush_on_close(void);
void test_wal_buffer_flush_on_manual_flush(void);
void test_strict_durability_recovery(void);
void test_fast_durability_batch_correctness(void);
void test_disk_quota_disabled_and_get_set(void);
void test_disk_quota_under_limit_no_delete(void);
void test_disk_quota_removes_old_segments_and_updates_index(void);
void test_disk_quota_keeps_active_and_last_segment(void);
void test_disk_quota_append_batch_reports_exceeded(void);
void test_disk_quota_handle_appends_report_exceeded(void);

int tsedge_test_failures = 0;

int main(void) {
    test_open_close();
    test_append_read_aggregate_csv();
    test_append_batch_zero_one_many();
    test_append_batch_multiple_blocks();
    test_flush_single_series();
    test_flush_empty_buffer();
    test_flush_all();
    test_flush_invalid_args();
    test_flush_before_export_csv();
    test_get_series_handle();
    test_append_handle_basic();
    test_append_batch_handle_basic();
    test_handle_invalid_args();
    test_handle_series_not_found();
    test_handle_after_reopen();
    test_handle_after_delete_documented_behavior();
    test_list_series_empty_database();
    test_list_series_multiple_series();
    test_list_series_stats_fields();
    test_list_series_invalid_args();
    test_list_series_after_reopen();
    test_verify_valid_database();
    test_verify_empty_database();
    test_verify_missing_metadata();
    test_verify_invalid_segment_filename();
    test_verify_truncated_segment();
    test_verify_invalid_args();
    test_corrupt_segment_magic();
    test_corrupt_segment_truncated();
    test_corrupt_segment_payload_size();
    test_corrupt_segment_point_count_zero();
    test_corrupt_segment_point_count_huge();
    test_corrupt_segment_timestamp_range();
    test_corrupt_segment_read_range_returns_error();
    test_corrupt_wal_checksum();
    test_corrupt_wal_torn_final_entry();
    test_corrupt_wal_batch_checksum();
    test_corrupt_wal_batch_torn_final_entry();
    test_corrupt_wal_batch_invalid_record_type();
    test_corrupt_wal_batch_invalid_point_count();
    test_random_bytes_segment_files();
    test_fuzz_like_random_segment_inputs();
    test_delete_series_basic();
    test_delete_series_files_removed();
    test_delete_series_after_reopen();
    test_delete_series_with_pending_wal();
    test_delete_one_series_keeps_others();
    test_delete_series_invalid_args();
    test_delete_series_then_recreate();
    test_series_stats_empty_and_buffered();
    test_series_stats_after_single_block_flush();
    test_series_stats_blocks_and_reopen();
    test_series_compression_stats();
    test_many_points_blocks_and_reopen();
    test_block_stats_aggregate_and_index();
    test_read_debug_stats_range_skip();
    test_read_stats_min_max_not_double_counted();
    test_read_range_callback_stops_full_scan();
    test_window_aggregate_basic();
    test_window_aggregate_boundary();
    test_window_aggregate_sparse();
    test_window_aggregate_empty_range();
    test_window_aggregate_invalid_args();
    test_window_aggregate_after_reopen();
    test_window_aggregate_multi_block();
    test_multiple_series();
    test_segment_rotation_creates_multiple_files();
    test_read_range_across_segments();
    test_aggregate_across_segments();
    test_reopen_rebuilds_multi_segment_index();
    test_wal_replay_with_segment_rotation();
    test_single_segment_database_still_works();
    test_delete_before_empty_series();
    test_delete_before_no_matching_segments();
    test_delete_before_removes_one_segment();
    test_delete_before_removes_multiple_segments();
    test_delete_before_keeps_partial_segment();
    test_delete_before_reopen();
    test_delete_before_append_after_delete();
    test_delete_before_wal_consistency();
    test_compression_roundtrip();
    test_block_header_validation();
    test_wal_recovery();
    test_wal_empty_replay();
    test_wal_incomplete_last_entry();
    test_wal_bad_checksum();
    test_wal_recovery_after_batch_append();
    test_wal_v2_point_recovery_compatibility();
    test_wal_batch_recovery_large();
    test_set_durability_invalid_args();
    test_wal_buffer_flush_on_close();
    test_wal_buffer_flush_on_manual_flush();
    test_strict_durability_recovery();
    test_fast_durability_batch_correctness();
    test_disk_quota_disabled_and_get_set();
    test_disk_quota_under_limit_no_delete();
    test_disk_quota_removes_old_segments_and_updates_index();
    test_disk_quota_keeps_active_and_last_segment();
    test_disk_quota_append_batch_reports_exceeded();
    test_disk_quota_handle_appends_report_exceeded();

    if (tsedge_test_failures != 0) {
        fprintf(stderr, "%d test(s) failed\n", tsedge_test_failures);
        return 1;
    }
    printf("all tests passed\n");
    return 0;
}
